baseURL = 'https://pawsey-internships.github.io/intro-unix-shell/'
languageCode = 'en-us'
title = 'Pawsey Intern Training: The Unix Shell'
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "pawsey"
disableLandingPageButton = true
